### ISSUE TITLE
labels: false option has no effect

### ISSUE THREAD

**Issue by sethvincent** [lightning-viz/lightning-circle#1]
Setting `options` to `{ labels: false }` didn't hide the labels as expected. 

I guess if I really didn't want to show labels I could just remove them from the data object.

Is this something that would be handled completely in this module? 

I can take a look & make a fix for this.

**Comment by mathisonian** [comment]
Do you think its redundant to be able to have a `labels` option and specify them (or not) in the data object? I think thats the change @freeman-lab made [here](https://github.com/lightning-viz/lightning-circle/commit/9d1da6ca2e3f2c3d3760df1cbaeddfc4d013884d), but we forgot to remove it from the `sample-options.json`. 

I don't really have a problem with letting a user explicitly turn them on/off in the options while leaving them in the data object. 

That commit above should show the logic needed to restore the option

**Comment by sethvincent** [comment]
For a basic usage example it does seem somewhat redundant. Maybe easier for programmatic usage to have a boolean option rather than change the data object, but I'm not convinced that's a big deal.

It looks like this is the only viz type that had the labels option, so I'd vote for making them all have the same API, include `data.labels` to show them or don't include them. That's an easy docs fix.

**Comment by mathisonian** [comment]
👍 sounds good to me

**Comment by sethvincent** [comment]
Updated the PR to remove mentions of `options.labels`: https://github.com/lightning-viz/lightning-circle/pull/2
